DROP TABLE IF EXISTS Cliente;
CREATE TABLE Cliente (
id INT NOT NULL,
nombre VARCHAR(150) NOT NULL,
apellido VARCHAR(150) NOT NULL,
nacimiento VARCHAR(10) NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Producto;
CREATE TABLE Producto (
id INT NOT NULL,
nombre VARCHAR(150) NOT NULL,
descripcion VARCHAR(150) NOT NULL,
precio INT NOT NULL,
PRIMARY KEY (id)
);

DROP TABLE IF EXISTS Venta;
CREATE TABLE Venta (
id INT NOT NULL,
producto VARCHAR(150) NOT NULL,
total INT NOT NULL,
PRIMARY KEY (id)
);